//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public int IdIncident { get; set; }
        public int IdTypeOfIncident { get; set; }
        public string Description { get; set; }
        public int IdEmployee { get; set; }
        public Nullable<int> IdResponseGroup { get; set; }
        public int EliminationTime { get; set; }
        public int IdMarkOfElimination { get; set; }
        public Nullable<System.DateTime> FinalEliminationTime { get; set; }
        public string DescriptionOfTheSolution { get; set; }
        public int Counter { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual MarkOfElimination MarkOfElimination { get; set; }
        public virtual ResponseGroup ResponseGroup { get; set; }
        public virtual TypeOfIncident TypeOfIncident { get; set; }
    }
}
